# Generated by Django 5.1 on 2024-09-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(default='Marketing Staff', max_length=100),
            preserve_default=False,
        ),
    ]
