# Generated by Django 4.2.15 on 2024-09-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(default='021-457-7890', help_text='Enter phone number', max_length=20),
        ),
    ]
